[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bracket"
version = "0.1"
dependencies = ["pygobject3", "pycairo", "pygobject-stubs"]

[tool.setuptools]
packages = ["bracket"]
# [project.scripts]
# bracket = "bracket.bracket:app"
