[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gedit"
version = "0.1"
dependencies = ["pygobject3", "pycairo", "pygobject-stubs"]

[tool.setuptools]
packages = ["gedit"]
[project.scripts]
gedit = "gedit.app:app"
