[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "zennote"
version = "0.1"
dependencies = ["pygobject3", "pycairo", "pygobject-stubs"]

[tool.setuptools]
packages = ["zennote"]
# [project.scripts]
# zennote = "zennote.zennote:app"
