[package]
name = "a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "a"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
tree-sitter-highlight = "0.25.4"
tree-sitter-python = "0.23.6"
