from __future__ import annotations

class HLEvent:
    Source = __Source
    Start = __Start
    End = __End

class __Source(HLEvent):
    _0: int
    _1: int
    def __new__(cls, arg0: int, arg1: int) -> __Source: ...
    def __getitem__(self, index: int) -> int: ... 
class __Start(HLEvent):
    _0: str
    def __new__(cls, arg0: str) -> __Start: ...
    def __getitem__(self, index: int) -> str: ...
class __End(HLEvent):
    def __new__(cls) -> __End: ...

class Highlighter:
    def __init__(self, recognized_names: list[str]) -> None: ...
    def highlight(self, code: str) -> list[HLEvent]: ...
    def set_language(self) -> None: ...
